stages:
  - test
  - dependency_scanning

test:
  1:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='UTC' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  2:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='Africa/Johannesburg' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  3:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='America/Los_Angeles' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  4:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='America/New_York' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  5:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='America/Santiago' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  6:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='Europe/London' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  7:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='Asia/Shanghai' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  8:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='Asia/Jakarta' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  9:
    image: node:8.15.1-alpine
    stage: test
    cache:
      paths:
        - node_modules/
    tags:
      - linux
    before_script:
      - apk add yarn
      - yarn install
    script:
      - TZ='Australia/Melbourne' yarn test --ci=true
    coverage: '/All\sfiles.*?\s+(\d+.\d+)/'

dependency_scanning:
  image: docker:stable
  stage: dependency_scanning
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
